version: "3.0"

services:
  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - '--web.enable-remote-write-receiver'
      - '--enable-feature=native-histograms'
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge