version: '3'
services:
  influxdb:
    image: influxdb:1.8 # Version 2.x introduces some breaking compatibility changes. K6 support for it comes via an extension
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - ./grafana:/etc/grafana/provisioning
    networks:
      - monitoring


networks:
  monitoring: